language: python
python:
 - "2.6"
 - "2.7"
install:
 - "sudo apt-get install libevent-dev"
 - "pip install -e . --use-mirrors"
 - "pip install coverage coveralls"
 - "psql -c 'create database ctable_test' -U postgres"
 - "curl http://127.0.0.1:5984/"
script:
 - "coverage run manage.py test --noinput"
services:
 - couchdb
after_success:
 - coverage report
 - coveralls